# Generated by Django 4.0.5 on 2022-07-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_rename_amenity_room_amenities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='discription',
            new_name='description',
        ),
    ]
