# Generated by Django 4.0.5 on 2022-07-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_rename_discription_room_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest',
            new_name='guests',
        ),
    ]
