# Generated by Django 4.0.5 on 2022-07-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_rename_guest_room_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bedroomes',
            new_name='bedrooms',
        ),
    ]
